name: emosense_ai
description: "A real-time sentiment analysis app powered by Gemini."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  fl_chart: ^1.1.1
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/orb.gif
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"