name: emosense_ai
description: "A real-time sentiment analysis app powered by Gemini."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  fl_chart: ^1.1.1
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: false

flutter:
  uses-material-design: true

  assets:
    - assets/orb.gif
    - assets/logo.png