name: emosense_ai
description: "A real-time sentiment analysis app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ye sab Left Side me hone chahiye (Not under flutter)
  google_generative_ai: ^0.4.0
  speech_to_text: ^6.6.1
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1
  flutter_tts: ^3.8.3  # Voice ke liye
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true